# Generated by Django 6.0b1 on 2025-10-30 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_screen_time', models.PositiveIntegerField(default=0, help_text='Total screen time in seconds for the day')),
                ('app_wise_data', models.JSONField(default=dict, help_text='App-wise screen time: {app: {hour: seconds, ...}, ...}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time', to='accounts.child')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
