# Generated by Django 6.0b1 on 2025-11-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_locationhistory_siteaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('app_name', models.CharField(max_length=255)),
                ('icon_url', models.URLField()),
                ('blocked_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='screentime',
            name='app_wise_data',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy: App-wise screen time. Use AppScreenTime model instead.'),
        ),
        migrations.CreateModel(
            name='AppScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField(help_text='Hour of day (0-23)')),
                ('seconds', models.PositiveIntegerField(help_text='Screen time in seconds for this app during this hour')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_entries', to='backend.app')),
                ('screen_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_screen_times', to='backend.screentime')),
            ],
            options={
                'ordering': ['hour'],
                'unique_together': {('screen_time', 'app', 'hour')},
            },
        ),
    ]
