# Generated by Django 6.0b1 on 2025-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='blocked_apps',
            field=models.JSONField(blank=True, default=list, help_text='List of blocked app package names'),
        ),
    ]
