# Generated by Django 6.0b1 on 2025-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_child_blocked_apps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='blocked_apps',
        ),
        migrations.AddField(
            model_name='child',
            name='restricted_apps',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of restricted apps with time limits: {"package.name": hours}'),
        ),
    ]
