# Generated by Django 6.0b1 on 2025-11-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_blocked_to_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Child profile picture', null=True, upload_to='child_profiles/'),
        ),
    ]
